### ISSUE TITLE
IJ N5 Library Has Missing Zarr Compression Class

### ISSUE THREAD

**Issue by AvocadoMoon** [saalfeldlab/n5#118]
# Problem
### Error Encounter
When attempting to use N5 AWS library in my IJ plugin, a null pointer exception gets thrown by the `CompressionAdapter` class. After putting IJ in debugging mode, downloading the source code for your N5 library, and adding breakpoints to this class it seems to be that within the try-catch block starting line 57 
`Class<? extends Compression> clazz = Class.forName(item.className());                                            
String type = ((Compression.CompressionType)clazz.getAnnotation(Compression.CompressionType.class)).value();`

### Root of Problem
This code gets executed to find the different class files with the annotation type `Compression`. The error arises from executing `.value()` when the `clazz` value is `org.janelia.saalfeldlab.n5.zarr.ZarrCompressor$Raw` alongside other attributes in this class structure. When trying to get the annotation with this variable the result is null which then causes this entire chain of errors.

**Comment by bogovicj** [comment]
Hi @AvocadoMoon ,

We observed something like this using old versions of n5-zarr, but [fixed it here](https://github.com/saalfeldlab/n5-zarr/commit/0afb158d0c17e7e38d7c0396b82efce769ae6458).

I expect this has something to do with the versions of artifacts you are depending on. Can you first make sure
you are depending on the latest versions of all the n5 artifacts you're using (the latest versions are tracked in the [pom-scijava](https://github.com/scijava/pom-scijava/blob/7e264d4d73afca8a1313b76ad48ba182bebdec6a/pom.xml#L1100-L1148)). 

If that doesn't address your issue, feel free to link us to your repo (if its public), or attach your pom.xml.

**Comment by AvocadoMoon** [comment]
Hello @bogovicj ,

Here is my [pom.xml](https://github.com/virtualcell/vcell-fiji/blob/37-single-panel-ij-plugin/view-simulation-results/pom.xml) file. I believe I have all of the latest Scijava versions of N5 libraries which is why I'm confused.

Also I forgot some crucial information about this bug, that is this error only appears when I create an artifact of the plugin I'm developing and use it within Fiji. I'm going to completely uninstall and reinstall Fiji to ensure it's not some strange caching where some outdated jars related to the N5 libraries are being used. If it's not that then I don't know what my next step can be.

**Comment by AvocadoMoon** [comment]
Surprisingly enough that seemed to fix it. All I had to do was uninstall and reinstall Fiji and the error just vanished. I guess I should have started my debugging with old reliable, "turn it off and on again".

So my best assumption is that there where some old cached N5 libraries in my Fiji installation that where being used.

**Comment by bogovicj** [comment]
Glad that did the trick @AvocadoMoon .
