### ISSUE TITLE
Last sentence of README is perhaps misleading?

### ISSUE THREAD

**Issue by adamltaylor** [saalfeldlab/n5#132]
The last sentence of the README is "Please do not take this project too seriously, we will see where it will get us and report back when more data is available."  I'm sure this made sense when it was written, but it seems to me that N5 is now a pretty established format, and, well, sort of has to be taken seriously.  (Whether the authors like it or not...)  I suggest deleting this line of the README.

**Comment by bogovicj** [comment]
We agree. https://github.com/saalfeldlab/n5/commit/afd3a959a7ede3cc489cd52fbcece705f410de5f

Thanks @adamltaylor
