### ISSUE TITLE
Make the specification versioned

### ISSUE THREAD

**Issue by ctrueden** [saalfeldlab/n5#15]
Arising from discussion at the DAIS Dec 2017 hackathon between @hanslovsky, @tpietzsch, @skalarproduktraum and myself: we want to avoid a future scenario where multiple different N5 files/datasets/etc. are incompatible (e.g., created at different points in history as the specification evolved), but programmatically indistinguishable. To avoid this, many formats embed the version as a primary piece of metadata.

**Comment by axtimwalde** [comment]
My plan was always to introduce a version tag when, for the first time, a new specification of the N5 format will be incompatible with a prior version, i.e. a new implementation of the new specification will not be able to load a file or dataset that was stored by an implementation of an older specification.  At that point, a missing version tag will be interpreted as version 0.  We are currently at version 0 and do not need a version tag.
