### ISSUE TITLE
Discussion: version in dataset attributes

### ISSUE THREAD

**Issue by aschampion** [saalfeldlab/n5#29]
This came up with @hanslovsky and @clbarnes during the https://github.com/aschampion/h2n5 hacking yesterday.

Should the n5 version be included in each dataset's attributes? At present, opening an N5 root will update the version attribute, even though existing datasets are untouched and therefore may be in an old format. It may be better to enforce this at the dataset level.

A consequential feature and/or bug of such a design is each dataset also becomes a valid n5 root.

**Comment by axtimwalde** [comment]
That only makes sense if the version is relevant for datasets only but
invariant with respect to groups (and their attributes).

I do not want to guarantee this, and therefore decided that the last
writer sets the field if it can open the root.  In cases where the
reader/writer is not compatible with data that was written by another
version, the version check at opening the root would corectly throw an
exception, and so we cannot combine data that cannot be opened by the
version declared in root.  I find this sound and easy and therefore
prefer this solution.

**Comment by aschampion** [comment]
Fair enough. A version introducing a breaking (major version) change to dataset structure then would need to hold the exclusive lock on the root attributes file while migrating all datasets. But this is pretty bikesheddy, and your decision is sane.
