### ISSUE TITLE
Deploy to maven repository

### ISSUE THREAD

**Issue by imagejan** [saalfeldlab/n5#36]
For other projects to use `n5` and related projects, it would be very helpful to have the artifacts deployed to a maven repository. As far as I can see from [`pom.xml`](https://github.com/saalfeldlab/n5/blob/9277f546b21b1c3c98f84a34ada295c50f727d38/pom.xml#L144-L149), you currently deploy to internal repositories only.

How about deploying to `maven.imagej.net` with the help of travis-ci.com? This can be set up using the SciJava script [`travisify.sh`](https://github.com/scijava/scijava-scripts/blob/c4fa09967fdcb65509bde5fc7e1cc7036d1f562a/travisify.sh).

**Comment by axtimwalde** [comment]
They are: https://github.com/saalfeldlab/maven
