### ISSUE TITLE
Version attribute for all groups?

### ISSUE THREAD

**Issue by aldanor** [saalfeldlab/n5#57]
Related questions have come up already, but not exactly this one: would it make sense to add an "n5" attribute to all the groups?

Is there any special about the root group? If you have "n5" version attribute in all groups and not just the root one, it just becomes the top-level group. It also makes it closer to Zarr where the version tag is stored for all groups regardless of their location.

**Comment by axtimwalde** [comment]
Considering this in cloud and filesystem storage may be useful but has unclear consequences for HDF5 backend.  I.e. not sure of I think this is a good idea.

**Comment by axtimwalde** [comment]
Still don't think this is a good idea, therefore closing.
