### ISSUE TITLE
Fiji

### ISSUE THREAD

**Issue by tischi** [saalfeldlab/n5#60]
@axtimwalde @joshmoore @ctrueden
Are there plans to ship all relevant n5 jars with Fiji any time soon?
The current master branch of bdv already depends on `n5-imglib2` and `n5`, so I guess it would be good to do so?

**Comment by imagejan** [comment]
One precondition for this is getting all n5-related artifacts managed by `pom-scijava`, see the pending PR https://github.com/scijava/pom-scijava/pull/93.

**Comment by axtimwalde** [comment]
Currently, there is an N5 update site: https://sites.imagej.net/N5/ that contains the dependency lighter components of N5 (N5 base, ImgLib2 bindings and HDF5 backend).  There is also the above mentioned pending pull request to pom-scijava...

**Comment by aschampion** [comment]
Being a complete ignoramus about Fiji-world, is there a reason n5-ij & n5-viewer aren't distributed via the N5 update site? They're one of the few things I find myself having to manually build for a minimal useful Fiji.

**Comment by axtimwalde** [comment]
Is n5-ij really useful?

**Comment by imagejan** [comment]
@aschampion wrote:
> one of the few things I find myself having to manually build

Well, manually building them should not be required. You can get the maven artifacts from jitpack.io:

https://jitpack.io/#saalfeldlab/n5-viewer

and `n5-ij` even from maven.scijava.org:

https://maven.scijava.org/#nexus-search;gav~~n5-ij~~~

But in general, I'd like to see the releases all available from maven.scijava.org as well : )

**Comment by axtimwalde** [comment]
N5-viewer has few hacks that are very specific to the lattice light sheet world, and also isn't on the light dependency side of things. Figuring out the dependencies to be distributed through an update site is very laborious.

**Comment by aschampion** [comment]
> Is n5-ij really useful?

Only in the sense that there are scripts in the wild that use it for reasons lost to time. It would of course be trivial to convert most to n5-imglib2 since it's thin.

> Figuring out the dependencies to be distributed through an update site is very laborious.

Understood.

Wasn't a request, just curious about the selection of what's in the update site.

**Comment by axtimwalde** [comment]
N5 now ships with Fiji https://github.com/fiji/fiji/commit/9b382dfa5cced460399696f9eb06d2d9b7000e8f
