### ISSUE TITLE
How to cite n5

### ISSUE THREAD

**Issue by tischi** [saalfeldlab/n5#62]
@axtimwalde @igorpisarev 

We are about to submit a publication where we are using n5(-aws-s3).

Is there a way to cite you in order to give you the deserved credit for your great work?

😃

**Comment by axtimwalde** [comment]
Not yet, but I am planning to submit a bioarxiv stub next week, so
please keep a placeholder

Pisarev et al. 2020 (manuscript in preparation)

to fill in during review---does that work?

**Comment by tischi** [comment]
Current text read like this:

_For efficient and open access we host all numerical data on github and stream the image data as n5-aws-s3 objects (Pisarev et al. 2020, manuscript in preparation,) from a publicly accessible object store._

OK? Make sense?

**Comment by axtimwalde** [comment]
It does, but please put it in the reference list as a reference, so you
can replace when the review requests come in.

Pisarev I. et al. (2020). N5---a hierarchical scalable n-dimensional
tensor-storage API with structured meta-data.  Manuscript in
preparation.

Thanks and good luck with the submission.  What is is that you are
doing there?

**Comment by tischi** [comment]
Thanks, will do!

1. Could you also already provide an authors list?
2. We are creating an application/resources to interactively browse multi-modal big image data. There are still few known bugs, but if you would like to beta test it, here is the current documentation: https://github.com/platybrowser/platybrowser-fiji#platybrowser-fiji

**Comment by tischi** [comment]
Thanks, will do!

1. Could you also already provide an authors list?
2. We are creating an application/resources to interactively browse multi-modal big image data. There are still some bugs, but if you would like to beta test it, here is the current documentation: https://github.com/platybrowser/platybrowser-fiji

**Comment by tischi** [comment]
@axtimwalde any updates on how to cite n5?

**Comment by axtimwalde** [comment]
The title and author list changed:
John A. Bogovic, Igor Pisarev, Philipp Hanslovsky, Neil Thistlethwaite, Stephan Saalfeld (2020), N5---a scalable Java API for hierarchies of chunked n-dimensional tensors and structured meta-data. Manuscript in preparation.

**Comment by oschrenk** [comment]
Is the manuscript available for download (yet)?

**Comment by bogovicj** [comment]
There is a doi to use for citing now:
https://zenodo.org/record/6578232#.Yo_SO1zMLEg
