### ISSUE TITLE
ambiguous text in spec

### ISSUE THREAD

**Issue by d-v-b** [saalfeldlab/n5#67]
Section 8 of the spec says "All chunks of a chunked dataset have the same size except for end-chunks that may be smaller, therefore..."

The word "size" here is ambiguous -- a chunk has several sizes (number of array elements, number of bytes in memory uncompressed, number of bytes in memory compressed). The text should be clarified to indicate which of these sizes (the first one) is constant across chunks.

**Comment by axtimwalde** [comment]
Thanks, this is a left over from an outdated version of the spec.
