### ISSUE TITLE
Any code example on how to use the package?

### ISSUE THREAD

**Issue by yliu7366** [saalfeldlab/n5#78]
Hi, I have limited Java programming experience. I would like to read a N5 file and save the data to more traditional volume files for my machine learning pipeline. I could use Fiji to load smaller sized N5 files and export to other formats on my laptop but it is difficult to do for larger sized N5 files so I need a programing way to do the work on servers. I really appreciate if there're examples to load N5 files into memory, for example, as numpy array, using this package. Thanks!

**Comment by bogovicj** [comment]
@yliu7366 ,

If you like python, you could try @constantinpape's : 
https://github.com/constantinpape/z5

We generally use [n5-imglib2](https://github.com/saalfeldlab/n5-imglib2), specifically the `open` and `save` methods in [N5Utils](https://github.com/saalfeldlab/n5-imglib2/blob/master/src/main/java/org/janelia/saalfeldlab/n5/imglib2/N5Utils.java#L1293-L1298)

I hope of of those will suit your needs

**Comment by yliu7366** [comment]
Very helpful. Closing the issue now. Thanks a lot!
