### ISSUE TITLE
make DatasetAttribute keys public

### ISSUE THREAD

**Issue by bogovicj** [saalfeldlab/n5#95]
The keys for `DatasetAttribute`s [are protected,](https://github.com/saalfeldlab/n5/blob/master/src/main/java/org/janelia/saalfeldlab/n5/DatasetAttributes.java#L48-L51) which means referencing them isn't possible from the outside, despite it
being [sometimes necessary](https://github.com/saalfeldlab/n5-zarr/blob/master/src/main/java/org/janelia/saalfeldlab/n5/zarr/N5ZarrWriter.java#L310).  

Since the fields are final, I don't see any harm in making them publicly visible, with the benefit that we can avoid "magic strings" as in the example above.

**Comment by cmhulbert** [comment]
I also would suggest renaming with SCREAMING_SNAKE_CASE since they are static final
